version: '3'
services:
  laravel:
    build:
      context: ./laravel
      dockerfile: .dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - database
  react:
    build:
      context: ./react-front
      dockerfile: .dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-front:/app
  database:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD:  "true"
      MYSQL_DATABASE: workmanager
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: